export const START_APP = 'START_APP';
export const CHANGE_STACK = 'CHANGE_STACK';
export const LIST_DEPARTMENTS = 'LIST_DEPARTMENTS';
export const LIST_CURRENCIES = 'LIST_CURRENCIES';
export const DEPARTMENT_GROUP = 'DEPARTMENT_GROUP';
export const OPERATION_TYPES = 'OPERATION_TYPES';
export const LOAD_STATUS = 'LOAD_STATUS';
export const GET_ORDERS = 'GET_ORDERS';
export const EDIT_USER_INFO = 'EDIT_USER_INFO';
export const ORDER_DATA = 'ORDER_DATA';
export const ORDER_DATA_COUNT = 'ORDER_DATA_COUNT';
export const SEARCH_PARAM = 'SEARCH_PARAM';
export const GET_ORDERS_MORE = 'GET_ORDERS_MORE';
export const SELECTED_DEPARTMENT = 'SELECTED_DEPARTMENT';
export const PAGINATION = 'PAGINATION';
export const SELECTED_ITEM_DEP = 'SELECTED_ITEM_DEP';
export const PRELOADER_MAIN = 'PRELOADER_MAIN';
export const ORDER_DATA_PAGINATION = 'ORDER_DATA_PAGINATION';
export const SETTINGS_APP = 'SETTINGS_APP';
// CHAT
export const CHAT_LIST = 'CHAT_LIST';
export const CHAT_LIST_SEARCH_PARAM = 'CHAT_LIST_SEARCH_PARAM';
export const CHAT_LIST_PAGINATION = 'CHAT_LIST_PAGINATION';
export const CHAT_LIST_PAGINATION_ITEMS = 'CHAT_LIST_PAGINATION_ITEMS';
export const SELECTED_CHAT_ITEM = 'SELECTED_CHAT_ITEM';
export const CHAT_LIST_MESSAGES = 'CHAT_LIST_MESSAGES';
export const CHAT_LIST_PAGINATION_MESSAGES = 'CHAT_LIST_PAGINATION_MESSAGES';
export const CHAT_MESSAGE_PAGINATION = 'CHAT_MESSAGE_PAGINATION';
export const ADD_NEW_CHAT = 'ADD_NEW_CHAT';

//CLIENTS
export const CLIENTS_LIST = 'CLIENTS_LIST';
export const CLIENTS_LIST_PAGINATION = 'CLIENTS_LIST_PAGINATION';
export const CLIENT_DETAILS = 'CLIENT_DETAILS';
export const CLIENTS_LIST_SEARCH_PARAM = 'CLIENTS_LIST_SEARCH_PARAM';
export const SELECT_CLIENT_CHAT = 'SELECT_CLIENT_CHAT';
export const CLEAR_SELECTED_CHAT = 'CLEAR_SELECTED_CHAT';
export const SELECTED_CLIENT_DETAILS = 'SELECTED_CLIENT_DETAILS';
export const SELECTED_CLIENT_ID = 'SELECTED_CLIENT_ID';
export const SELECT_CLIENT_ORDERS = 'SELECT_CLIENT_ORDERS';

// modal

export const MODAL_CREATE_NEW_CHAT = 'MODAL_CREATE_NEW_CHAT';
