export const START_APP = 'START_APP';
export const CHANGE_STACK = 'CHANGE_STACK';
export const LIST_DEPARTMENTS = 'LIST_DEPARTMENTS';
export const LIST_CURRENCIES = 'LIST_CURRENCIES';
export const DEPARTMENT_GROUP = 'DEPARTMENT_GROUP';
export const OPERATION_TYPES = 'OPERATION_TYPES';
export const LOAD_STATUS = 'LOAD_STATUS';
